name: cellpose
dependencies:
  - python==3.8.5
  - pip
  - pip:
    - PyQt5
    - PyQt5.sip
    - numpy>=1.20.0
    - numba>=0.43.1
    - scipy
    - torch>=1.6
    - opencv-python-headless
    - pyqtgraph>=0.11.0rc0
    - natsort
    - google-cloud-storage
    - tqdm
    - tifffile
    - fastremap
    - cellpose
    
  
python -m cellpose --train --dir D:/3_py_project/cellpose_seg/train/ --test_dir D:/3_py_project/cellpose_seg/test/ --pretrained_model cyto --chan 2 --chan2 1 --learning_rate 0.1 --weight_decay 0.0001 --n_epochs 10